### ISSUE TITLE
Data for peru is incorrect

### ISSUE THREAD

**Issue by monstrfolk** [scott-wyatt/countrystatesjs#16]
The json file lists a bunch of states, but all the states listed are cities.

**Comment by scott-wyatt** [comment]
Thanks! I'm open to any pull requests.

**Comment by jpauley-veem** [comment]
I think you can close this. This user may be looking for Regions instead of Provinces. The Peru province list looks fine to me.

https://en.wikipedia.org/wiki/Provinces_of_Peru
